# Generated by Django 4.0.3 on 2023-05-28 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0010_program_alter_student_course_delete_course'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='status',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
