# Generated by Django 4.0.3 on 2023-05-28 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0011_alter_program_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='program',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
