# Generated by Django 4.0.3 on 2023-05-28 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0012_alter_program_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='student',
            old_name='course',
            new_name='program',
        ),
    ]
