# Generated by Django 4.0.3 on 2023-05-31 09:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0014_academicyear_pi_data_venue_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='dob',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='gender',
        ),
    ]
