# Generated by Django 4.0.3 on 2023-06-02 04:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0017_alter_semester_unique_together'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='semester',
            unique_together={('academic_year', 'semester')},
        ),
    ]
