# Generated by Django 4.0.3 on 2023-06-02 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0018_alter_semester_unique_together'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Class',
        ),
    ]
