# Generated by Django 4.0.3 on 2023-06-05 21:39

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0019_delete_class'),
    ]

    operations = [
        migrations.AlterField(
            model_name='semester',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='semester',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
