# Generated by Django 4.0.3 on 2023-06-07 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0023_rename_venue_id_venue_block_rename_name_venue_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='venue',
            name='common_name',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
