# Generated by Django 4.0.3 on 2023-06-10 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0024_venue_common_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pi_data',
            name='registration_number',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AlterField(
            model_name='venue',
            name='number',
            field=models.CharField(max_length=15),
        ),
    ]
