# Generated by Django 4.0.3 on 2023-06-14 08:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('attendance', '0025_alter_pi_data_registration_number_alter_venue_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='FingerStore_Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_number', models.CharField(max_length=50, unique=True)),
                ('hash_number_lecturer', models.CharField(max_length=250, unique=True)),
                ('student_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.student')),
            ],
        ),
        migrations.CreateModel(
            name='FingerStore_Lecturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_number', models.CharField(max_length=50, unique=True)),
                ('hash_number_lecturer', models.CharField(max_length=250, unique=True)),
                ('lecturer_number', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='attendance.userprofile')),
            ],
        ),
    ]
